package com.aueb.distributed.mapreduce.enums;

public enum Command {
	FRIEND_RECOMMENDATION_BY_EVENT_ATTENDANCE,
	EVENT_LIST_AROUND_MEMBER_BY_DISTANCE, 
	REQUEST_STATUS_BY_REQUEST_ID, 
	REQUEST_RESULT_BY_REQUEST_ID,
	EVENT_VOTING,
	FRIEND_LIST,
	EVENT_LIST,
	BEFRIEND,
	UNFRIEND,
	MEMBER_INFORMATION,
	SEND_PUBLIC_MESSAGE, 
	SEND_PRIVATE_MESSAGE,
	SEND_COMMAND_RETURN,
	QUIT
}
